INSERT INTO categorie (id, categoria) VALUES(1, 'gov');
INSERT INTO categorie (id, categoria) VALUES(94, 'mobilità');
INSERT INTO categorie (id, categoria) VALUES(95, 'segnalazioni');
INSERT INTO categorie (id, categoria) VALUES(96, 'volontariato');
INSERT INTO categorie (id, categoria) VALUES(97, 'scuola');
INSERT INTO categorie (id, categoria) VALUES(98, 'ambiente');
INSERT INTO categorie (id, categoria) VALUES(99, 'uffici comunali');
INSERT INTO categorie (id, categoria) VALUES(100, 'salute');
INSERT INTO categorie (id, categoria) VALUES(101, 'bonus');
INSERT INTO categorie (id, categoria) VALUES(102, 'sport');
INSERT INTO categorie (id, categoria) VALUES(103, 'cultura e servizi');
INSERT INTO categorie (id, categoria) VALUES(104, 'tributi');
INSERT INTO categorie (id, categoria) VALUES(46, 'cie');
INSERT INTO categorie (id, categoria) VALUES(47, 'suolo_pubblico');
INSERT INTO categorie (id, categoria) VALUES(48, 'cambio_residenza');
INSERT INTO categorie (id, categoria) VALUES(49, 'tari');