INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(153, 'Quali sono i contatti per la guardia medica e per interagire con l''ASL', NULL, 100);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(2, 'Nella mia area sono aperti ristoranti, pizzerie, pasticcerie e altre attività di ristorazione  È consentito il consumo di cibi e bevande al loro interno  Fino a che ora posso restare ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(6, 'La consegna e il trasporto dei mobili può avvenire ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(8, 'È consentito svolgere assemblee condominiali in presenza ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(9, 'Nella nozione delle fiere, vietate dal Dpcm, rientrano anche manifestazioni locali con prevalente carattere commerciale ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(10, 'Quali sono le regole valide nella mia area per gli spostamenti  Ci sono dei divieti ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(11, 'Gli spostamenti devono essere giustificati in qualche modo  È necessario produrre un’autodichiarazione ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(12, 'Posso andare ad assistere un parente o un amico non autosufficienti ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(13, 'Sono separato/divorziato, posso andare a trovare i miei figli minorenni ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(14, 'Posso andare a trovare parenti o congiunti ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(15, 'Sono consentiti gli spostamenti per fare visita alle persone detenute in carcere ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(17, 'Chi è sottoposto alle misure della quarantena o dell’isolamento si può spostare ', NULL, 100);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(18, 'Cosa devo fare in caso di sintomi (tosse, raffreddore, febbre) ', NULL, 100);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(19, 'È possibile fare la spesa in un comune diverso da quello in cui si abita ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(22, 'Cosa significa “comprovate esigenze lavorative”  I lavoratori autonomi come faranno a dimostrare le “comprovate esigenze lavorative” ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(24, 'Chi si trova fuori dal proprio domicilio, abitazione o residenza potrà rientrarvi ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(25, 'È possibile raggiungere la seconda casa ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(26, 'Ci si può spostare per andare in chiesa o negli altri luoghi di culto ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(28, 'è possibile fare la passeggiata con il cane ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(30, 'È consentito fare attività motoria ', NULL, 102);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(32, 'L’accesso a parchi e giardini pubblici è consentito  Quali sono i parchi aperti ', NULL, 102);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(33, 'Posso utilizzare la bicicletta ', NULL, 102);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(34, 'Posso usare l’automobile con persone non conviventi ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(101, 'Quali negozi ed esercizi commerciali trovo aperti nei giorni feriali e quali nei giorni festivi ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(104, 'i mercati rionali sono aperti ', NULL, 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(106, 'Si può fare attività sportiva all''aperto ', NULL, 102);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(107, 'Come funziona il servizio di smaltimento di rifiuti ingombranti ', NULL, 98);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(108, 'orario ecocentro', NULL, 98);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(109, 'regole della raccolta differenziata', NULL, 98);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(110, 'Ci sono contributi/sgravi ai quali si può accedere a causa della pandemia ', NULL, 101);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(111, 'Servizi ordinari e straordinari in ambito socio-assistenziale previsti dal Comune', NULL, 103);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(112, 'Quali sono gli orari e numeri telefono delle biblioteche comunali aperte ed il loro indirizzo ', NULL, 103);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(116, 'Sono disponibili servizi per la consegna a domicilio della spesa e dei farmaci ', NULL, 103);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(119, 'La sosta a pagamento è attiva o sospesa ', NULL, 94);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(120, 'Variazioni della viabilità per lavori in corso', NULL, 94);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(123, 'vorrei sapere i contagiati e la situazione del mio comune', NULL, 100);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(151, 'Chi devo contattare per fare una vaccinazione ', NULL, 100);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(152, 'Dove posso fare il tampone ', NULL, 100);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(155, 'Necessito di informazioni sul servizio mensa per le scuole', NULL, 97);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(157, 'Cosa devo fare per iscrivere i miei figli a scuola ', NULL, 97);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(159, 'Quali sono i contatti per usufruire del servizio di scuolabus ', NULL, 97);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(166, 'Informazioni sugli impianti sportivi comunali aperti e regole per lo sport', NULL, 102);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(168, 'Modalità di accesso agli uffici comunali: prenotazioni e orari per appuntamenti in sede; servizi online', NULL, 99);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(169, 'Qual è l''orario di apertura dei cimiteri ', NULL, 99);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(179, 'Informazioni sulle modalità di partecipazione associazioni di volontariato', NULL, 96);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(180, 'Raccolta di beni di prima necessità per i poveri', NULL, 96);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(181, 'Quali sono le associazioni presenti nel comune (indirizzo, telefono, e-mail) ', NULL, 96);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(1000, 'Con quali modalità si paga la TARI ', NULL, 104);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(1002, 'devo pagare una tassa ma non mi è ancora arrivato il bollettino cosa fare  ', NULL, 104);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(1003, 'Quali sono le scadenze di pagamento delle varie tasse comunali ', NULL, 104);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(1004, 'Calcolo IMU', NULL, 104);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(2001, 'Come si prende la carta d''identità elettronica ', NULL, 99);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(2002, 'Rinnovo carta d''identità costi', NULL, 99);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(3001, 'Come posso richiedere il cambio di residenza ', NULL, 99);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(1, 'Ci sono differenze all’interno del territorio nazionale', 'Dal 6 novembre 2020, le norme distinguono tre diverse aree (note come gialla, arancione, rossa), con restrizioni differenti, sulla base di parametri oggettivi relativi al livello di rischio e allo scenario epidemico della zona interessata. È necessario verificare in quale area rientra il proprio Comune per identificare il quadro delle norme e delle restrizioni previste per la propria area.', 1);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(117, 'Come avere informazioni sulla ZTL', NULL, 94);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(162, 'Come faccio a segnalare problemi, disservizi e guasti? Come segnalo comportamenti non corretti: quali sono i contatti della Polizia Municipale?', NULL, 95);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(114, 'Contatti dello sportello territoriale del Centro per l''Impiego', NULL, 103);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(115, 'Cos''è SPID?', NULL, 103);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(118, 'Blocchi del traffico e limitazioni alla circolazione per veicoli inquinanti', NULL, 94);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(121, 'richiesta contrassegno parcheggio disabili', NULL, 94);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(124, 'Quali sono i dati della qualità dell''aria nel comune?', NULL, 98);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(131, 'Copertura della fibra ottica a un dato indirizzo', NULL, 103);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(132, 'Quali sono le opere infrastrutturali in costruzione?', NULL, 103);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(156, 'Le attività scolastiche vengono svolte in presenza', NULL, 97);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(190, 'Richiesta della tessera elettorale, diritto di voto ed iscrizione all''albo degli scrutatori', NULL, 99);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(195, 'Informazioni su matrimoni civili', NULL, 99);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(200, 'Canili e gattili municipali, adozioni di animali', NULL, 99);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(210, 'Case popolari', NULL, 99);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(1005, 'Quali pagamenti posso effettuare tramite PagoPa per il Comune', NULL, 104);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(1006, 'TASI: variazioni del metodo di calcolo', NULL, 104);
INSERT INTO domande (id, domanda, risposta_default, fk_categoria) VALUES(3010, 'Modalità di richiesta dei certificati anagrafici', NULL, 99);